parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                SC_PAYMENT_SOURCE_DECORATOR:  App\Util\MySQL\PaymentSourceDecorator
                NATURAL_SORT:                 App\Util\MySQL\NaturalSort
                FIRST:                        App\Util\MySQL\First
                JSON_ARRAYAGG:                App\Util\MySQL\JsonArrayAgg
                JSON_OBJECT:                  App\Util\MySQL\JsonObject
                JSON_ARRAY:                   Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArray
                JSON_EXTRACT:                 Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_CONTAINS:                Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                JSON_UNQUOTE:                 Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
                CAST:                         Oro\ORM\Query\AST\Functions\Cast
                DATE_FORMAT:                  Oro\ORM\Query\AST\Functions\String\DateFormat
                GROUP_CONCAT:                 Oro\ORM\Query\AST\Functions\String\GroupConcat
