jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:s.v\Z'
            default_timezone: 'UTC'
    visitors:
        xml:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
