# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        initial_optimize:
            quality: 100
            post_processors:
                pngquant: { quality: "25" }
        thumb_35x35:
            quality: 100
            filters:
                upscale: { min: [35, 35] }
                thumbnail: { size: [35, 35], mode: outbound }
        thumb_150x150:
            quality: 100
            filters:
                upscale: { min: [150, 150] }
                thumbnail: { size: [150, 150], mode: outbound }
        thumb_300x300:
            quality: 100
            filters:
                upscale: { min: [300, 300] }
                thumbnail: { size: [300, 300], mode: outbound }
