# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumb_400x400:
            quality: 100
            filters:
                upscale: { min: [400, 400] }
                thumbnail: { size: [400, 400], mode: outbound }
        thumb_600x600:
            quality: 100
            filters:
                upscale: { min: [600, 600] }
                thumbnail: { size: [600, 600], mode: outbound }
