twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/Api/V1/Common/Resources/views/grid':  'api_grid'
        '%kernel.project_dir%/src/Api/V1/Common/Resources/views/email': 'api_email'
        '%kernel.project_dir%/src/Api/V1/Common/Resources/views/report': 'api_report'
