persistence:
  title: "Persistence"
  fields: ['enabled', 'level', 'identity']
  children:
    security:
      title: 'Security'
      children:
        access_token:
          title: 'AccessToken'
          class: App\Entity\AccessToken
        auth_code:
          title: 'AuthCode'
          class: App\Entity\AuthCode
        client:
          title: 'Client'
          class: App\Entity\Client
        refresh_token:
          title: 'RefreshToken'
          class: App\Entity\RefreshToken

        space:
          title: 'Space'
          class: App\Entity\Space
        role:
          title: 'Role'
          class: App\Entity\Role
        user:
          title: 'User'
          class: App\Entity\User
        user_invite:
          title: 'UserInvite'
          class: App\Entity\UserInvite
        user_log:
          title: 'UserLog'
          class: App\Entity\UserLog
        user_phone:
          title: 'UserPhone'
          class: App\Entity\UserPhone

    lead:
      title: 'Lead'
      children:
        lead:
          title: 'Lead'
          class: App\Entity\Lead\Lead
        referral:
          title: 'Referral'
          class: App\Entity\Lead\Referral
        referral_phone:
          title: 'ReferralPhone'
          class: App\Entity\Lead\ReferralPhone
        organization:
          title: 'Organization'
          class: App\Entity\Lead\Organization
        organization_phone:
          title: 'OrganizationPhone'
          class: App\Entity\Lead\OrganizationPhone
        referrer_type:
          title: 'Referrer Type'
          class: App\Entity\Lead\ReferrerType
        activity:
          title: 'Activity'
          class: App\Entity\Lead\Activity
        activity_status:
          title: 'Activity Status'
          class: App\Entity\Lead\ActivityStatus
        activity_type:
          title: 'Activity Type'
          class: App\Entity\Lead\ActivityType
        care_type:
          title: 'Care Type'
          class: App\Entity\Lead\CareType
        state_change_reason:
          title: 'State Change Reason'
          class: App\Entity\Lead\StateChangeReason

    common:
      title: 'Common'
      children:
        care_level:
          title: 'CareLevel'
          class: App\Entity\CareLevel
          route: api_admin_care_level_list
        city_state_zip:
          title: 'CityStateZip'
          class: App\Entity\CityStateZip
          route: api_admin_city_state_zip_list

        event_definition:
          title: 'EventDefinition'
          class: App\Entity\EventDefinition
          route: api_admin_event_definition_list
        payment_source:
          title: 'PaymentSource'
          class: App\Entity\PaymentSource
          route: api_admin_payment_source_list
        notification_type:
          title: 'NotificationType'
          class: App\Entity\NotificationType
          route: api_admin_notification_type_list
        notification:
          title: 'Notification'
          class: App\Entity\Notification
          route: api_admin_notification_list
        change_log:
          title: 'ChangeLog'
          class: App\Entity\ChangeLog
          route: api_admin_change_log_list

        relationship:
          title: 'Relationship'
          class: App\Entity\Relationship
          route: api_admin_relationship_list
        salutation:
          title: 'Salutation'
          class: App\Entity\Salutation
          route: api_admin_salutation_list
        speciality:
          title: 'Speciality'
          class: App\Entity\Speciality
          route: api_admin_speciality_list
        responsible-person-role:
          title: 'ResponsiblePersonRole'
          class: App\Entity\ResponsiblePersonRole
          route: api_admin_responsible_person_role_list

        allergen:
          title: 'Allergen'
          class: App\Entity\Allergen
          route: api_admin_allergen_list
        diagnosis:
          title: 'Diagnosis'
          class: App\Entity\Diagnosis
          route: api_admin_diagnosis_list
        diet:
          title: 'Diet'
          class: App\Entity\Diet
          route: api_admin_diet_list
        medical_history_condition:
          title: 'MedicalHistoryCondition'
          class: App\Entity\MedicalHistoryCondition
          route: api_admin_medical_history_condition_list
        medication:
          title: 'Medication'
          class: App\Entity\Medication
          route: api_admin_medication_list
        medication_form_factor:
          title: 'MedicationFormFactor'
          class: App\Entity\MedicationFormFactor
          route: api_admin_medication_form_factor_list

        physician:
          title: 'Physician'
          class: App\Entity\Physician
          route: api_admin_physician_list
        responsible_person:
          title: 'ResponsiblePerson'
          class: App\Entity\ResponsiblePerson
          route: api_admin_responsible_person_list
        responsible_person_phone:
          title: 'ResponsiblePersonPhone'
          class: App\Entity\ResponsiblePersonPhone
          route: api_admin_responsible_person_phone_list

        insurance_company:
          title: 'InsuranceCompany'
          class: App\Entity\InsuranceCompany
          route: api_admin_insurance_company_list

    assessment:
      title: 'Assessment'
      children:
        care_level:
          title: 'CareLevel'
          class: App\Entity\Assessment\CareLevel
          route: api_admin_care_level_list
        care_level_group:
          title: 'CareLevelGroup'
          class: App\Entity\Assessment\CareLevelGroup
          route: api_admin_care_level_group_list
        category:
          title: 'Category'
          class: App\Entity\Assessment\Category
          route: api_admin_category_list
        form:
          title: 'Form'
          class: App\Entity\Assessment\Form
          route: api_admin_form_list
        form_category:
          title: 'FormCategory'
          class: App\Entity\Assessment\FormCategory
          route: api_admin_form_category_list
        row:
          title: 'Row'
          class: App\Entity\Assessment\Row
          route: api_admin_row_list

    apartment:
      title: 'Apartment'
      class: App\Entity\Apartment
      route: api_admin_apartment_list
    apartment_room:
      title: 'ApartmentRoom'
      class: App\Entity\ApartmentRoom
      route: api_admin_apartment_room_list
    apartment_bed:
      title: 'ApartmentBed'
      class: App\Entity\ApartmentBed
      route: api_admin_apartment_bed_list

    facility:
      title: 'Facility'
      class: App\Entity\Facility
      route: api_admin_facility_list
    facility_room:
      title: 'FacilityRoom'
      class: App\Entity\FacilityRoom
      route: api_admin_facility_room_list
    facility_bed:
      title: 'FacilityBed'
      class: App\Entity\FacilityBed
      route: api_admin_facility_bed_list
    dining_room:
      title: 'DiningRoom'
      class: App\Entity\DiningRoom
      route: api_admin_dining_room_list

    region:
      title: 'Region'
      class: App\Entity\Region
      route: api_admin_region_list

    resident:
      title: 'Resident'
      children:
        resident:
          title: 'Resident'
          class: App\Entity\Resident
          route: api_admin_resident_list
        resident_allergen:
          title: 'ResidentAllergen'
          class: App\Entity\ResidentAllergen
          route: api_admin_resident_allergen_list
        resident_diagnosis:
          title: 'ResidentDiagnosis'
          class: App\Entity\ResidentDiagnosis
          route: api_admin_resident_diagnosis_list
        resident_diet:
          title: 'ResidentDiet'
          class: App\Entity\ResidentDiet
          route: api_admin_resident_diet_list
        resident_event:
          title: 'ResidentEvent'
          class: App\Entity\ResidentEvent
          route: api_admin_resident_event_list
        resident_medical_history_condition:
          title: 'ResidentMedicalHistoryCondition'
          class: App\Entity\ResidentMedicalHistoryCondition
          route: api_admin_resident_medical_history_condition_list
        resident_medication:
          title: 'ResidentMedication'
          class: App\Entity\ResidentMedication
          route: api_admin_resident_medication_list
        resident_medication_allergy:
          title: 'ResidentMedicationAllergy'
          class: App\Entity\ResidentMedicationAllergy
          route: api_admin_resident_medication_allergy_list
        resident_phone:
          title: 'ResidentPhone'
          class: App\Entity\ResidentPhone
          route: api_admin_resident_phone_list
        resident_physician:
          title: 'ResidentPhysician'
          class: App\Entity\ResidentPhysician
          route: api_admin_resident_physician_list
        resident_rent:
          title: 'ResidentRent'
          class: App\Entity\ResidentRent
          route: api_admin_resident_rent_list
        resident_responsible_person:
          title: 'ResidentResponsiblePerson'
          class: App\Entity\ResidentResponsiblePerson
          route: api_admin_resident_responsible_person_list
        health_insurance:
          title: 'HealthInsurance'
          class: App\Entity\HealthInsurance
          route: api_admin_health_insurance_list

        admission:
          title: 'ResidentAdmission'
          class: App\Entity\ResidentAdmission
          route: api_admin_resident_admission_list

        assessment:
          title: 'Assessment'
          children:
            assessment:
              title: 'Assessment'
              class: App\Entity\Assessment\Assessment
              route: api_admin_assessment_list
            assessment_row:
              title: 'AssessmentRow'
              class: App\Entity\Assessment\AssessmentRow
              route: api_admin_assessment_row_list

activity:
  title: "Activity"
  fields: ['enabled']
  children:
    resident:
      title: "Resident"
      children:
        change-physician:
          title: "Change the resident's physician"

report:
  title: "Report"
  fields: ['enabled']
  children:
    resident:
      title: "Resident Reports"
      children:
        profile:
          title: "Profile : Profile for selected resident / all residents"
        profile-no-admission:
          title: "Profile : Profile for selected resident / all residents (pre-admit)"
        face-sheet:
          title: "FACE Sheet : FACE Sheet for selected resident / all residents"
        face-sheet-no-admission:
          title: "FACE Sheet : FACE Sheet for selected resident / all residents (pre-admit)"
        detailed-roster:
          title: "Detailed Roster : Resident Roster, sorted by room number, with Responsible Person and Physician contact information"
        simple-roster:
          title: "Simple Roster : Simple list of Residents, sorted by Room Number"
        dietary-restrictions:
          title: "Dietary Restrictions : Dietary Restrictions Report"
        sixty-days-roster:
          title: "60 Days Roster : 60 Days Roster Report"
        event-list:
          title: "Events : List of Residents Events"
    form:
      title: "Forms Reports"
      children:
        birthday-list:
          title: "Birthday list : List of all residents birthdays, Monthly"
        blood-pressure:
          title: "Blood Pressure : Blood pressure charting"
        bowel-movement:
          title: "Bowel movement : Bowel Movement tracking form, Weekly"
        changeover-notes:
          title: "Changeover notes : Shift Changeover Notes, Daily"
        manicure:
          title: "Manicure : Manicure Tracking Form, Monthly"
        meal-monitor:
          title: "Meal Monitor : Meal Consumption Tracking Form, Weekly"
        medication-chart:
          title: "MAR - Medication Chart : Medication Chart for Selected Resident, Monthly"
        medication-chart-no-admission:
          title: "MAR - Medication Chart : Medication Chart for Selected Resident, Monthly (pre-admit)"
        medication-chart-all:
          title: "MAR - Medication Chart : Medication Charts for all Resident, Monthly"
        medication-chart-blank:
          title: "MAR - Medication Chart : Blank Medication Chart"
        medication-list-resident:
          title: "Medications List Selected Resident : Medications list for selected resident"
        medication-list-resident-no-admission:
          title: "Medications List Selected Resident : Medications list for selected resident (pre-admit)"
        medication-list-all:
          title: "Medications List All Residents : Medications list for all residents."
        night-activity:
          title: "Night activity : Night Activity Tracking Form, Daily"
        room-audit:
          title: "Room Audit : Resident Room Audit form"
        shower-skin-inspection:
          title: "Shower Skin Inspection Selected Resident : Shower Skin Inspection for current selected resident"
        shower-skin-list:
          title: "Shower Skin Inspection All : Shower Skin Inspection for current selected facility residents, ordered by Room Number."
    room:
      title: "Room Reports"
      children:
        payor:
          title: "Payor Report : Monthly Payor Report."
        room-list:
          title: "Room : List of Rooms, with occupants and room rent rates."
        room-rent:
          title: "Room Rent : Monthly Rent Report."
        room-rent-master:
          title: "Room Rent Master : Historical Rent Graphs, Data - for Finance Use only."
        room-rent-master-new:
          title: "Room Rent Master: New! : Monthly Rent Master Report."
        room-vacancy:
          title: "Room Vacancy List : List of Vacant Rooms, by Facility. Calculated as of today"
        room-occupancy:
          title: "Room Occupancy Rates : Facility Occupancy Rate Summary (calculated as of today)"
    physician:
      title: "Physicians Reports"
      children:
        simple:
          title: "Physician Roster Simple : List of physicians, with contact information and resident count"
        full:
          title: "Physician Roster Full : List of physicians, with contact information and resident count"
    assessment:
      title: "Assessment Reports"
      children:
        blank:
          title: "Assessment Report (Blank)"
        filled:
          title: "Assessment Report (Filled)"
    lead:
      title: "Lead Reports"
      children:
        lead:
          title: "Generate Lead List Report"
        referral:
          title: "Generate Referral List Report"
        activity:
          title: "Generate Activity List Report"
