resident:
  title: 'Resident Reports'
  show_in_list: true
  reports:
    profile:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getProfileReport
      title: 'Profile : Profile for selected resident / all residents'
      show_in_list: true
      formats: ['pdf']
      parameters:
        discontinued: true
        resident:
          select_all: true
    profile-no-admission:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getProfileNoAdmissionReport
      title: 'Profile : Profile for selected resident / all residents'
      show_in_list: false
      formats: ['pdf']
      template: 'profile'
      parameters:
        discontinued: true
        resident:
          select_all: false
    face-sheet:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getFaceSheetReport
      title: 'FACE Sheet : FACE Sheet for selected resident / all residents'
      show_in_list: true
      formats: ['pdf']
      parameters:
        resident:
          select_all: true
    face-sheet-no-admission:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getFaceSheetNoAdmissionReport
      title: 'FACE Sheet : FACE Sheet for selected resident / all residents'
      show_in_list: false
      formats: ['pdf']
      template: 'face-sheet'
      parameters:
        resident:
          select_all: false
    detailed-roster:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getDetailedRosterReport
      title: 'Detailed Roster : Resident Roster, sorted by room number, with Responsible Person and Physician contact information'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    simple-roster:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getSimpleRosterReport
      title: 'Simple Roster : Simple list of Residents, sorted by Room Number'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    dietary-restrictions:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getDietaryRestrictionsReport
      title: 'Dietary Restrictions : Dietary Restrictions Report'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    sixty-days-roster:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getSixtyDaysReport
      title: '60 Days Roster : 60 Days Roster Report'
      show_in_list: true
      formats: ['csv']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    event-list:
      service: App\Api\V1\Admin\Service\Report\ResidentReportService::getEventReport
      title: 'Events : List of Residents Events'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
        date_from: "m/d/Y"
        date_to: "m/d/Y"
form:
  title: 'Forms Reports'
  show_in_list: true
  reports:
    birthday-list:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getBirthdayListReport
      title: 'Birthday list : List of all residents birthdays, Monthly'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    blood-pressure:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getBloodPressureChartingReport
      title: 'Blood Pressure : Blood pressure charting'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    bowel-movement:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getBowelMovementReport
      title: 'Bowel movement : Bowel Movement tracking form, Weekly'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    changeover-notes:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getChangeoverNotesReport
      title: 'Changeover notes : Shift Changeover Notes, Daily'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    manicure:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getManicureReport
      title: 'Manicure : Manicure Tracking Form, Monthly'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    meal-monitor:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMealMonitorReport
      title: 'Meal Monitor : Meal Consumption Tracking Form, Weekly'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    medication-chart:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationChartReport
      title: 'MAR - Medication Chart : Medication Chart for Selected Resident, Monthly'
      show_in_list: true
      formats: ['pdf']
      template: 'medication-chart'
      parameters:
        resident:
          select_all: true
    medication-chart-all:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationChartReport
      title: 'MAR - Medication Chart : Medication Charts for all Resident, Monthly'
      show_in_list: true
      formats: ['pdf']
      template: 'medication-chart'
      parameters:
        group:
          select_all: true
    medication-chart-blank:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationChartBlankReport
      title: 'MAR - Medication Chart : Blank Medication Chart'
      show_in_list: true
      formats: ['pdf']
      template: 'medication-chart-blank'
      parameters:
        group:
          select_all: true
    medication-chart-no-admission:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationChartNoAdmissionReport
      title: 'MAR - Medication Chart : Medication Chart / Medical Charts for Selected Resident / all residents, Monthly'
      show_in_list: false
      formats: ['pdf']
      template: 'medication-chart'
      parameters:
        resident:
          select_all: false
    medication-list-resident:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationListReport
      title: 'Medications List Selected Resident : Medications list for selected resident'
      show_in_list: true
      formats: ['pdf']
      template: 'medication-list'
      parameters:
        discontinued: true
        resident:
            select_all: true
    medication-list-all:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationListReport
      title: 'Medications List All Residents : Medications list for all residents'
      show_in_list: true
      formats: ['pdf']
      template: 'medication-list'
      parameters:
        discontinued: true
        group:
            select_all: true
    medication-list-resident-no-admission:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getMedicationListNoAdmissionReport
      title: 'Medications List Selected Resident : Medications list for selected resident'
      show_in_list: false
      formats: ['pdf']
      template: 'medication-list'
      parameters:
        discontinued: true
        resident:
          select_all: false
    night-activity:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getNightActivityReport
      title: 'Night activity : Night Activity Tracking Form, Daily'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    room-audit:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getRoomAuditReport
      title: 'Room Audit : Resident Room Audit form'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
    shower-skin-inspection:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getShowerSkinInspectionReport
      title: 'Shower Skin Inspection Selected Resident : Shower Skin Inspection for current selected resident'
      show_in_list: true
      formats: ['pdf']
      parameters:
        resident:
          select_all: true
    shower-skin-list:
      service: App\Api\V1\Admin\Service\Report\FormReportService::getShowerSkinInspectionReport
      title: 'Shower Skin Inspection All : Shower Skin Inspection for current selected facility residents, ordered by Room Number'
      show_in_list: true
      formats: ['pdf']
      template: 'shower-skin-inspection'
      parameters:
        group:
          select_all: true
room:
  title: 'Room Reports'
  show_in_list: true
  reports:
    payor:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getPayorReport
      title: 'Payor Report : Monthly Payor Report'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    room-list:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomListReport
      title: 'Room : Simple Rent Roster'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    room-rent:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomRentReport
      title: 'Room Rent : Monthly Rent Report'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    room-rent-master:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomRentMasterReport
      title: 'Room Rent Master : Historical Rent Graphs, Data - for Finance Use only'
      show_in_list: true
      formats: ['pdf']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    room-rent-master-new:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomRentMasterNewReport
      title: 'Room Rent Master: New! : Monthly Rent Master Report'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
        date: "m/d/Y"
    room-vacancy:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomVacancyListReport
      title: 'Room Vacancy List : List of Vacant Rooms, by Facility. Calculated as of today'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
    room-occupancy:
      service: App\Api\V1\Admin\Service\Report\RoomReportService::getRoomOccupancyRateReport
      title: 'Room Occupancy Rates : Facility Occupancy Rate Summary (calculated as of today)'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true

physician:
  title: 'Physicians Reports'
  show_in_list: true
  reports:
    simple:
      service: App\Api\V1\Admin\Service\Report\PhysicianReportService::getSimpleReport
      title: 'Physician Roster Simple : List of physicians, with contact information and resident count'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true
    full:
      service: App\Api\V1\Admin\Service\Report\PhysicianReportService::getFullReport
      title: 'Physician Roster Full : List of physicians, with contact information and resident count'
      show_in_list: true
      formats: ['pdf', 'csv']
      parameters:
        group:
          select_all: true

assessment:
  title: 'Assessment Reports'
  show_in_list: false
  reports:
    blank:
      service: App\Api\V1\Admin\Service\Report\AssessmentReportService::getBlankReport
      title: 'Assessment Report (Blank)'
      show_in_list: false
      formats: ['pdf']
      parameters:
        resident:
          select_all: false
    filled:
      service: App\Api\V1\Admin\Service\Report\AssessmentReportService::getFilledReport
      title: 'Assessment Report (Filled)'
      show_in_list: false
      formats: ['pdf']
      parameters:
        resident:
          select_all: false

lead:
  title: 'Lead Reports'
  show_in_list: false
  reports:
    lead:
      service: App\Api\V1\Admin\Service\Report\LeadReportService::getLeadReport
      title: 'Generate Lead List Report'
      show_in_list: false
      formats: ['csv']
      parameters:
        date_from: "m/d/Y"
        date_to: "m/d/Y"
    referral:
      service: App\Api\V1\Admin\Service\Report\LeadReportService::getReferralReport
      title: 'Generate Referral List Report'
      show_in_list: false
      formats: ['csv']
      parameters:
        date_from: "m/d/Y"
        date_to: "m/d/Y"
    activity:
      service: App\Api\V1\Admin\Service\Report\LeadReportService::getActivityReport
      title: 'Generate Activity List Report'
      show_in_list: false
      formats: ['csv']
      parameters:
        date_from: "m/d/Y"
        date_to: "m/d/Y"