parameters:
    core.model.user.provider.class: App\Model\User\UserProvider
    core.entity.user.class: App\Entity\User
    core.repository.user.class: App\Repository\UserRepository
    count.age.extension.class: App\Util\Twig\Extension\CountAgeExtension
    format.day.extension.class: App\Util\Twig\Extension\FormatDayExtension
    rent.period.extension.class: App\Util\Twig\Extension\RentPeriodExtension
    phone.type.extension.class: App\Util\Twig\Extension\PhoneTypeExtension
    adission.type.extension.class: App\Util\Twig\Extension\AdmissionTypeExtension

services:
    core.model.user.provider:
        class: %core.model.user.provider.class%
        arguments: ['@core.user.repository']
    core.user.manager:
        class: Doctrine\ORM\EntityManager
        arguments: ['%core.entity.user.class%']
        factory: ['@doctrine', getManagerForClass]
    core.user.repository:
        class: %core.repository.user.class%
        arguments: ['%core.entity.user.class%']
        factory: ['@core.user.manager', getRepository]
    count.age.extension:
        class: %count.age.extension.class%
        tags:
          - { name: twig.extension }
    format.day.extension:
        class: %format.day.extension.class%
        tags:
          - { name: twig.extension }
    rent.period.extension:
        class: %rent.period.extension.class%
        tags:
          - { name: twig.extension }
    phone.type.extension:
        class: %phone.type.extension.class%
        tags:
          - { name: twig.extension }
    adission.type.extension:
        class: %adission.type.extension.class%
        tags:
          - { name: twig.extension }