parameters:
    core.model.user.provider.class: App\Model\User\UserProvider
    core.entity.user.class: App\Entity\User
    core.repository.user.class: App\Repository\UserRepository

services:
    core.model.user.provider:
        class: %core.model.user.provider.class%
        arguments: ['@core.user.repository']
    core.user.manager:
        class: Doctrine\ORM\EntityManager
        arguments: ['%core.entity.user.class%']
        factory: ['@doctrine', getManagerForClass]
    core.user.repository:
        class: %core.repository.user.class%
        arguments: ['%core.entity.user.class%']
        factory: ['@core.user.manager', getRepository]
