common_annotations:
    resource: '../src/Api/V1/Common/Controller/'
    type:     annotation
    defaults: {_format: json}

admin_annotations:
    resource: '../src/Api/V1/Admin/Controller/'
    type:     annotation
    defaults: {_format: json}

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

